using System.Text;

namespace core.jarvis.data.RLS
{
    /// <summary>
    /// Helper class for applying PostgreSQL Row-Level Security policies from the RLSPolicyRegistry.
    /// Generates and executes SQL statements to enable RLS, force RLS, and create policies.
    /// </summary>
    public class RLSMigrationHelper
    {
        private readonly PgClient _pgClient;
        private readonly RLSPolicyRegistry _registry;

        /// <summary>
        /// Initializes a new instance of RLSMigrationHelper.
        /// </summary>
        /// <param name="pgClient">The PostgreSQL client for executing SQL statements.</param>
        /// <param name="registry">The RLS policy registry containing policy definitions.</param>
        public RLSMigrationHelper(PgClient pgClient, RLSPolicyRegistry registry)
        {
            _pgClient = pgClient ?? throw new ArgumentNullException(nameof(pgClient));
            _registry = registry ?? throw new ArgumentNullException(nameof(registry));
        }

        /// <summary>
        /// Applies all PostgreSQL RLS policies from the registry to the database.
        /// Skips wildcard patterns (e.g., "*_component") - use ApplyComponentPolicyAsync for those.
        /// </summary>
        /// <returns>A task representing the asynchronous operation.</returns>
        public async Task ApplyPoliciesAsync()
        {
            var policies = _registry.GetAllPolicies()
                .Where(p => p.HasPostgresPolicy)
                .Where(p => !IsWildcardPattern(p.TableName))
                .ToList();

            foreach (var policy in policies)
            {
                await ApplyPolicyAsync(policy);
            }
        }

        /// <summary>
        /// Generates a complete SQL migration script for all registered RLS policies.
        /// Includes enabling RLS, forcing RLS, dropping existing policies, and creating new policies.
        /// Skips wildcard patterns - those must be resolved to specific table names.
        /// </summary>
        /// <returns>The complete SQL migration script as a string.</returns>
        public string GenerateMigrationScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- RLS Migration Script");
            sb.AppendLine("-- Generated by RLSMigrationHelper");
            sb.AppendLine($"-- Generated at: {DateTime.UtcNow:O}");
            sb.AppendLine();

            var policies = _registry.GetAllPolicies()
                .Where(p => p.HasPostgresPolicy)
                .Where(p => !IsWildcardPattern(p.TableName))
                .ToList();

            if (!policies.Any())
            {
                sb.AppendLine("-- No PostgreSQL-native RLS policies found.");
                return sb.ToString();
            }

            // Group policies by table for cleaner output
            var policiesByTable = policies.GroupBy(p => p.TableName);

            foreach (var tableGroup in policiesByTable)
            {
                var tableName = tableGroup.Key;
                sb.AppendLine($"-- Policies for table: {tableName}");
                sb.AppendLine();

                // Enable RLS on table
                sb.AppendLine($"ALTER TABLE \"{tableName}\" ENABLE ROW LEVEL SECURITY;");

                // Force RLS even for table owner
                sb.AppendLine($"ALTER TABLE \"{tableName}\" FORCE ROW LEVEL SECURITY;");
                sb.AppendLine();

                foreach (var policy in tableGroup)
                {
                    sb.AppendLine(GeneratePolicySql(policy));
                    sb.AppendLine();
                }
            }

            return sb.ToString();
        }

        /// <summary>
        /// Resolves a wildcard pattern (e.g., "*_component") and applies the policy to a specific table.
        /// </summary>
        /// <param name="componentTableName">The specific component table name (e.g., "account_component").</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        public async Task ApplyComponentPolicyAsync(string componentTableName)
        {
            if (string.IsNullOrWhiteSpace(componentTableName))
            {
                throw new ArgumentException("Component table name cannot be null or empty.", nameof(componentTableName));
            }

            // Find the wildcard pattern policy
            var wildcardPolicy = _registry.GetAllPolicies()
                .Where(p => p.HasPostgresPolicy)
                .FirstOrDefault(p => IsWildcardPattern(p.TableName) && MatchesWildcardPattern(componentTableName, p.TableName));

            if (wildcardPolicy == null)
            {
                throw new InvalidOperationException($"No wildcard policy found that matches table '{componentTableName}'.");
            }

            // Create a resolved policy with the specific table name
            var resolvedPolicy = new RLSPolicy
            {
                TableName = componentTableName,
                Type = wildcardPolicy.Type,
                PolicyName = $"{wildcardPolicy.PolicyName}_{componentTableName}",
                UsingExpression = wildcardPolicy.UsingExpression,
                WithCheckExpression = wildcardPolicy.WithCheckExpression
            };

            await ApplyPolicyAsync(resolvedPolicy);
        }

        /// <summary>
        /// Applies a single RLS policy to the database.
        /// </summary>
        private async Task ApplyPolicyAsync(RLSPolicy policy)
        {
            // Enable RLS on table
            await _pgClient.ExecuteAsync($"ALTER TABLE \"{policy.TableName}\" ENABLE ROW LEVEL SECURITY;");

            // Force RLS even for table owner
            await _pgClient.ExecuteAsync($"ALTER TABLE \"{policy.TableName}\" FORCE ROW LEVEL SECURITY;");

            // Drop existing policy if exists
            await _pgClient.ExecuteAsync($"DROP POLICY IF EXISTS \"{policy.PolicyName}\" ON \"{policy.TableName}\";");

            // Create new policy
            var createPolicySql = GenerateCreatePolicySql(policy);
            await _pgClient.ExecuteAsync(createPolicySql);
        }

        /// <summary>
        /// Generates the complete SQL for a policy (drop + create).
        /// </summary>
        private string GeneratePolicySql(RLSPolicy policy)
        {
            var sb = new StringBuilder();

            // Drop existing policy if exists
            sb.AppendLine($"DROP POLICY IF EXISTS \"{policy.PolicyName}\" ON \"{policy.TableName}\";");

            // Create new policy
            sb.AppendLine(GenerateCreatePolicySql(policy));

            return sb.ToString();
        }

        /// <summary>
        /// Generates the CREATE POLICY SQL statement for a policy.
        /// </summary>
        private string GenerateCreatePolicySql(RLSPolicy policy)
        {
            var sb = new StringBuilder();

            sb.Append($"CREATE POLICY \"{policy.PolicyName}\" ON \"{policy.TableName}\"");

            // Add FOR clause based on policy type
            var forClause = policy.Type switch
            {
                PolicyType.Select => " FOR SELECT",
                PolicyType.Insert => " FOR INSERT",
                PolicyType.Update => " FOR UPDATE",
                PolicyType.Delete => " FOR DELETE",
                PolicyType.All => " FOR ALL",
                _ => " FOR ALL"
            };
            sb.Append(forClause);

            // Add USING clause (for SELECT, UPDATE, DELETE, ALL)
            if (policy.Type != PolicyType.Insert && !string.IsNullOrEmpty(policy.UsingExpression))
            {
                sb.Append($" USING ({policy.UsingExpression})");
            }

            // Add WITH CHECK clause (for INSERT, UPDATE, ALL)
            if (policy.Type == PolicyType.Insert || policy.Type == PolicyType.Update || policy.Type == PolicyType.All)
            {
                var checkExpression = policy.WithCheckExpression ?? policy.UsingExpression;
                if (!string.IsNullOrEmpty(checkExpression))
                {
                    sb.Append($" WITH CHECK ({checkExpression})");
                }
            }

            sb.Append(";");

            return sb.ToString();
        }

        /// <summary>
        /// Determines if a table name is a wildcard pattern.
        /// </summary>
        private static bool IsWildcardPattern(string tableName)
        {
            return tableName.Contains('*');
        }

        /// <summary>
        /// Checks if a table name matches a wildcard pattern.
        /// </summary>
        private static bool MatchesWildcardPattern(string tableName, string pattern)
        {
            // Simple wildcard matching: "*_component" matches "account_component"
            if (pattern.StartsWith("*"))
            {
                var suffix = pattern.Substring(1);
                return tableName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase);
            }

            if (pattern.EndsWith("*"))
            {
                var prefix = pattern.Substring(0, pattern.Length - 1);
                return tableName.StartsWith(prefix, StringComparison.OrdinalIgnoreCase);
            }

            // For patterns like "foo*bar"
            var parts = pattern.Split('*');
            if (parts.Length == 2)
            {
                return tableName.StartsWith(parts[0], StringComparison.OrdinalIgnoreCase) &&
                       tableName.EndsWith(parts[1], StringComparison.OrdinalIgnoreCase);
            }

            return false;
        }
    }
}
