namespace core.jarvis.api.tests.Configuration;

/// <summary>
/// Centralized configuration constants for test scenarios.
/// Provides standardized test parameters and timeouts across the test suite.
/// </summary>
public static class TestConstants
{
    /// <summary>
    /// Integration test configuration for process and HTTP testing.
    /// </summary>
    public static class Integration
    {
        /// <summary>
        /// Port number for running the test Azure Functions instance.
        /// Chosen to avoid conflicts with common development ports.
        /// </summary>
        public const int TestPort = 7072;
        
        /// <summary>
        /// Timeout in milliseconds for process termination.
        /// Allows sufficient time for graceful shutdown.
        /// </summary>
        public const int ProcessTerminationTimeoutMs = 5000;
        
        /// <summary>
        /// Maximum wait time in seconds for application startup.
        /// Balances test execution time with startup reliability.
        /// </summary>
        public const int MaxAppStartupWaitSeconds = 60;
        
        /// <summary>
        /// HTTP client timeout for individual requests during testing.
        /// Prevents hanging tests while allowing for slower operations.
        /// </summary>
        public const int HttpClientTimeoutSeconds = 5;
        
        /// <summary>
        /// Delay between startup checks in milliseconds.
        /// Prevents excessive polling while maintaining responsiveness.
        /// </summary>
        public const int StartupCheckDelayMs = 1000;
        
        /// <summary>
        /// Interval for status logging during startup wait.
        /// Provides visibility into long startup processes.
        /// </summary>
        public const int StatusLogIntervalSeconds = 5;
    }

    /// <summary>
    /// Token service testing configuration.
    /// </summary>
    public static class TokenTesting
    {
        /// <summary>
        /// Test access token expiration time in minutes for test scenarios.
        /// Short duration appropriate for testing without impacting test execution time.
        /// </summary>
        public const int TestAccessTokenExpirationMinutes = 15;
        
        /// <summary>
        /// Expected size in bytes for refresh tokens generated by the service.
        /// Matches the implementation's 32-byte random token generation.
        /// </summary>
        public const int ExpectedRefreshTokenSizeBytes = 32;
    }

    /// <summary>
    /// Database testing configuration.
    /// </summary>
    public static class Database
    {
        /// <summary>
        /// Standard PostgreSQL port for test database connections.
        /// Default port used in test connection strings.
        /// </summary>
        public const int TestPostgreSqlPort = 5432;
        
        /// <summary>
        /// BCrypt cost factor for test password hashing.
        /// Lower cost for faster test execution while maintaining security testing.
        /// </summary>
        public const int TestBCryptCostFactor = 10;
        
        /// <summary>
        /// Standard timeout for database operations in tests.
        /// Prevents hanging tests while allowing for complex operations.
        /// </summary>
        public const int DatabaseOperationTimeoutMs = 30000;
    }

    /// <summary>
    /// Performance and timing test configuration.
    /// </summary>
    public static class Performance
    {
        /// <summary>
        /// Standard delay for testing timing-sensitive operations.
        /// Short enough for fast test execution, long enough for timing verification.
        /// </summary>
        public const int StandardTestDelayMs = 500;
        
        /// <summary>
        /// Extended delay for testing longer operations.
        /// Used when testing operations that require more time to complete.
        /// </summary>
        public const int ExtendedTestDelayMs = 1000;
        
        /// <summary>
        /// Maximum iterations for performance testing loops.
        /// Balances test coverage with execution time.
        /// </summary>
        public const int MaxPerformanceTestIterations = 10;
        
        /// <summary>
        /// Standard batch size for bulk operations testing.
        /// Reasonable size for testing bulk operations without excessive time.
        /// </summary>
        public const int StandardBatchSize = 5;
    }

    /// <summary>
    /// Security testing configuration.
    /// </summary>
    public static class Security
    {
        /// <summary>
        /// Minimum entropy threshold for cryptographic testing.
        /// Ensures generated values meet security requirements.
        /// </summary>
        public const int MinimumEntropyThreshold = 10;
        
        /// <summary>
        /// Expected hash length for SHA256 operations.
        /// Standard output size for SHA256 hashing algorithm.
        /// </summary>
        public const int Sha256HashLengthBytes = 32;
        
        /// <summary>
        /// Expected BCrypt hash length for password verification.
        /// Standard length for BCrypt hash strings.
        /// </summary>
        public const int BCryptHashLength = 60;
        
        /// <summary>
        /// Minimum acceptable JWT secret key length.
        /// Security requirement for HMAC-SHA256 signing.
        /// </summary>
        public const int MinJwtSecretKeyLength = 32;
    }
}