using core.jarvis.Data;

namespace core.jarvis.api.Models;

/// <summary>
/// Component representing version history and snapshots for UIStudio resources.
/// Provides comprehensive change tracking, rollback capabilities, and audit trails.
/// Table: ui_studio_version (automatic snake_case mapping)
/// </summary>
public record UIStudioVersion : IComponent
{
    /// <summary>
    /// Unique identifier for this component instance.
    /// </summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    /// <summary>
    /// The entity this component belongs to.
    /// Required by IComponent interface.
    /// </summary>
    public Guid OwnerEntityId { get; set; }

    /// <summary>
    /// Entity ID of the resource this version snapshot represents.
    /// Maps to resource_entity_id in database.
    /// </summary>
    public Guid ResourceEntityId { get; init; }

    /// <summary>
    /// Type of resource: "page", "layout", "component_binding".
    /// Maps to resource_type in database.
    /// </summary>
    public string ResourceType { get; init; } = string.Empty;

    /// <summary>
    /// Type of version: "auto", "manual", "published", "restore", "branch", "merge".
    /// Maps to version_type in database.
    /// </summary>
    public string VersionType { get; init; } = "auto";

    /// <summary>
    /// Version number for this snapshot.
    /// Maps to version_number in database.
    /// </summary>
    public int VersionNumber { get; init; }

    /// <summary>
    /// Complete snapshot of the resource state stored as JSON.
    /// Contains the full component data at the time of this version.
    /// Maps to snapshot_data in database.
    /// </summary>
    public Dictionary<string, object>? SnapshotData { get; init; }

    /// <summary>
    /// Summary of changes made in this version.
    /// Maps to change_summary in database.
    /// </summary>
    public string? ChangeSummary { get; init; }

    /// <summary>
    /// Detailed change log stored as JSON.
    /// Contains field-level change information.
    /// Maps to change_details in database.
    /// </summary>
    public Dictionary<string, object>? ChangeDetails { get; init; }

    /// <summary>
    /// Entity ID of the user who created this version.
    /// Maps to created_by_entity_id in database.
    /// </summary>
    public Guid CreatedByEntityId { get; init; }

    /// <summary>
    /// When this version was created.
    /// Maps to created_at in database.
    /// </summary>
    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Optional label for this version (e.g., "Initial Release", "Bug Fix").
    /// Maps to version_label in database.
    /// </summary>
    public string? VersionLabel { get; init; }

    /// <summary>
    /// Optional version tag (e.g., "v1.0.0", "v2.1.3").
    /// Maps to version_tag in database.
    /// </summary>
    public string? VersionTag { get; init; }

    /// <summary>
    /// Whether this version represents a published state.
    /// Maps to is_published in database.
    /// </summary>
    public bool IsPublished { get; init; } = false;

    /// <summary>
    /// When this version was published (if applicable).
    /// Maps to published_at in database.
    /// </summary>
    public DateTime? PublishedAt { get; init; }

    /// <summary>
    /// Whether this version is marked for auto-deletion.
    /// Maps to is_auto_generated in database.
    /// </summary>
    public bool IsAutoGenerated { get; init; } = false;

    /// <summary>
    /// Parent version number if this is based on another version.
    /// Maps to parent_version_number in database.
    /// </summary>
    public int? ParentVersionNumber { get; init; }

    /// <summary>
    /// Parent version ID if this is based on another version.
    /// Maps to parent_version_id in database.
    /// </summary>
    public Guid? ParentVersionId { get; init; }

    /// <summary>
    /// Branch version ID for merge operations.
    /// Maps to branch_version_id in database.
    /// </summary>
    public Guid? BranchVersionId { get; init; }

    /// <summary>
    /// Branch name for version branching scenarios.
    /// Maps to branch_name in database.
    /// </summary>
    public string? BranchName { get; init; }

    /// <summary>
    /// Tags associated with this version for categorization.
    /// Stored as comma-separated string.
    /// </summary>
    public string? Tags { get; init; }

    /// <summary>
    /// Size of the snapshot data in bytes.
    /// Maps to snapshot_size_bytes in database.
    /// </summary>
    public long SnapshotSizeBytes { get; init; }

    /// <summary>
    /// Checksum/hash of the snapshot data for integrity verification.
    /// Maps to snapshot_checksum in database.
    /// </summary>
    public string? SnapshotChecksum { get; init; }

    /// <summary>
    /// When this version was last updated.
    /// Required by IComponent interface.
    /// </summary>
    public DateTime LastUpdated { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Retention policy for this version.
    /// Determines how long this version should be kept.
    /// Maps to retention_policy in database.
    /// </summary>
    public string? RetentionPolicy { get; init; }

    /// <summary>
    /// When this version should be automatically deleted (if applicable).
    /// Maps to delete_after in database.
    /// </summary>
    public DateTime? DeleteAfter { get; init; }
}