<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>568deb06-425f-48cc-8015-3be15f4f4d23</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Identity" Version="1.8.2" />
      <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.13.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FJarvis.Data\FJarvis.Data.csproj" />
      <ProjectReference Include="..\FJarvis.Traits.FlightCentre\FJarvis.Traits.FlightCentre.csproj" />
    </ItemGroup>

</Project>
