using core.jarvis.Data;
using core.jarvis.api.Models;
using core.jarvis.Exceptions;
using Microsoft.Extensions.Logging;
using System.Text.Json;
using System.Security.Cryptography;
using System.Text;

namespace core.jarvis.api.Handlers;

/// <summary>
/// Handler for managing UIStudioVersion components.
/// Provides operations for creating, managing, and querying version history and snapshots.
/// </summary>
public class UIStudioVersionHandler : ComponentHandler<UIStudioVersion>
{
    public UIStudioVersionHandler(
        IDataContext dataContext,
        ILogger<UIStudioVersionHandler> logger)
        : base(dataContext, logger)
    {
    }

    /// <summary>
    /// Creates a new version snapshot for a resource.
    /// </summary>
    /// <param name="version">The version snapshot to create</param>
    /// <returns>The created version component</returns>
    /// <exception cref="ArgumentException">Thrown when version configuration is invalid</exception>
    public async Task<UIStudioVersion> CreateVersion(UIStudioVersion version)
    {
        ValidateVersionConfiguration(version);
        
        // Calculate snapshot size and checksum if snapshot data is provided
        if (version.SnapshotData != null)
        {
            var jsonData = JsonSerializer.Serialize(version.SnapshotData);
            var versionWithMetadata = version with
            {
                SnapshotSizeBytes = Encoding.UTF8.GetByteCount(jsonData),
                SnapshotChecksum = CalculateChecksum(jsonData)
            };
            
            await DataContext.Commit(versionWithMetadata);
            return versionWithMetadata;
        }

        await DataContext.Commit(version);
        return version;
    }

    /// <summary>
    /// Creates an automatic version snapshot for a resource.
    /// </summary>
    /// <param name="resourceEntityId">Entity ID of the resource</param>
    /// <param name="resourceType">Type of the resource</param>
    /// <param name="snapshotData">Current state of the resource</param>
    /// <param name="createdByEntityId">Entity ID of the user creating the version</param>
    /// <param name="changeSummary">Summary of changes</param>
    /// <returns>The created version component</returns>
    public async Task<UIStudioVersion> CreateAutoVersion(
        Guid resourceEntityId, 
        string resourceType, 
        Dictionary<string, object> snapshotData,
        Guid createdByEntityId,
        string? changeSummary = null)
    {
        var nextVersionNumber = await GetNextVersionNumber(resourceEntityId);
        
        var jsonData = JsonSerializer.Serialize(snapshotData);
        var version = new UIStudioVersion
        {
            ResourceEntityId = resourceEntityId,
            ResourceType = resourceType,
            VersionNumber = nextVersionNumber,
            SnapshotData = snapshotData,
            CreatedByEntityId = createdByEntityId,
            IsAutoGenerated = true,
            ChangeSummary = changeSummary ?? $"Auto-generated version {nextVersionNumber}",
            SnapshotSizeBytes = Encoding.UTF8.GetByteCount(jsonData),
            SnapshotChecksum = CalculateChecksum(jsonData),
            RetentionPolicy = "auto_cleanup",
            DeleteAfter = DateTime.UtcNow.AddDays(30) // Auto-generated versions kept for 30 days
        };

        return await CreateVersion(version);
    }

    /// <summary>
    /// Creates a published version snapshot for a resource.
    /// </summary>
    /// <param name="resourceEntityId">Entity ID of the resource</param>
    /// <param name="resourceType">Type of the resource</param>
    /// <param name="snapshotData">Current state of the resource</param>
    /// <param name="createdByEntityId">Entity ID of the user creating the version</param>
    /// <param name="versionLabel">Label for this version</param>
    /// <param name="changeSummary">Summary of changes</param>
    /// <returns>The created version component</returns>
    public async Task<UIStudioVersion> CreatePublishedVersion(
        Guid resourceEntityId, 
        string resourceType, 
        Dictionary<string, object> snapshotData,
        Guid createdByEntityId,
        string? versionLabel = null,
        string? changeSummary = null)
    {
        var nextVersionNumber = await GetNextVersionNumber(resourceEntityId);
        
        var jsonData = JsonSerializer.Serialize(snapshotData);
        var version = new UIStudioVersion
        {
            ResourceEntityId = resourceEntityId,
            ResourceType = resourceType,
            VersionNumber = nextVersionNumber,
            SnapshotData = snapshotData,
            CreatedByEntityId = createdByEntityId,
            IsPublished = true,
            IsAutoGenerated = false,
            VersionLabel = versionLabel ?? $"Release v{nextVersionNumber}",
            ChangeSummary = changeSummary,
            SnapshotSizeBytes = Encoding.UTF8.GetByteCount(jsonData),
            SnapshotChecksum = CalculateChecksum(jsonData),
            RetentionPolicy = "permanent" // Published versions kept permanently
        };

        return await CreateVersion(version);
    }

    /// <summary>
    /// Gets all versions for a specific resource.
    /// </summary>
    /// <param name="resourceEntityId">Entity ID of the resource</param>
    /// <param name="includeAutoGenerated">Whether to include auto-generated versions</param>
    /// <returns>List of versions ordered by version number descending</returns>
    public async Task<List<UIStudioVersion>> GetResourceVersions(Guid resourceEntityId, bool includeAutoGenerated = true)
    {
        var query = DataContext.Query()
            .WithAll<UIStudioVersion>(v => v.ResourceEntityId == resourceEntityId);

        if (!includeAutoGenerated)
        {
            query = query.WithAll<UIStudioVersion>(v => !v.IsAutoGenerated);
        }

        var results = await query.ToEntityComponents();
        var versions = new List<UIStudioVersion>();

        foreach (var result in results)
        {
            var handler = DataContext.For<UIStudioVersionHandler>(result.Key);
            var version = await handler.Get();
            if (version != null)
            {
                versions.Add(version);
            }
        }

        return versions.OrderByDescending(v => v.VersionNumber).ToList();
    }

    /// <summary>
    /// Gets a specific version by resource and version number.
    /// </summary>
    /// <param name="resourceEntityId">Entity ID of the resource</param>
    /// <param name="versionNumber">Version number to retrieve</param>
    /// <returns>The version if found, null otherwise</returns>
    public async Task<UIStudioVersion?> GetVersion(Guid resourceEntityId, int versionNumber)
    {
        var query = DataContext.Query()
            .WithAll<UIStudioVersion>(v => v.ResourceEntityId == resourceEntityId && v.VersionNumber == versionNumber);

        var results = await query.ToEntityComponents();
        var versionEntity = results.FirstOrDefault();
        
        if (versionEntity.Key == Guid.Empty) return null;

        var handler = DataContext.For<UIStudioVersionHandler>(versionEntity.Key);
        return await handler.Get();
    }

    /// <summary>
    /// Gets the latest version for a resource.
    /// </summary>
    /// <param name="resourceEntityId">Entity ID of the resource</param>
    /// <param name="publishedOnly">Whether to only consider published versions</param>
    /// <returns>The latest version if found, null otherwise</returns>
    public async Task<UIStudioVersion?> GetLatestVersion(Guid resourceEntityId, bool publishedOnly = false)
    {
        var versions = await GetResourceVersions(resourceEntityId, !publishedOnly);
        
        if (publishedOnly)
        {
            return versions.Where(v => v.IsPublished).FirstOrDefault();
        }

        return versions.FirstOrDefault();
    }

    /// <summary>
    /// Gets all published versions for a resource.
    /// </summary>
    /// <param name="resourceEntityId">Entity ID of the resource</param>
    /// <returns>List of published versions ordered by version number descending</returns>
    public async Task<List<UIStudioVersion>> GetPublishedVersions(Guid resourceEntityId)
    {
        var query = DataContext.Query()
            .WithAll<UIStudioVersion>(v => v.ResourceEntityId == resourceEntityId && v.IsPublished);

        var results = await query.ToEntityComponents();
        var versions = new List<UIStudioVersion>();

        foreach (var result in results)
        {
            var handler = DataContext.For<UIStudioVersionHandler>(result.Key);
            var version = await handler.Get();
            if (version != null)
            {
                versions.Add(version);
            }
        }

        return versions.OrderByDescending(v => v.VersionNumber).ToList();
    }

    /// <summary>
    /// Gets versions that are eligible for cleanup based on retention policies.
    /// </summary>
    /// <returns>List of versions that can be deleted</returns>
    public async Task<List<UIStudioVersion>> GetVersionsForCleanup()
    {
        var query = DataContext.Query()
            .WithAll<UIStudioVersion>(v => v.DeleteAfter != null && v.DeleteAfter <= DateTime.UtcNow);

        var results = await query.ToEntityComponents();
        var versions = new List<UIStudioVersion>();

        foreach (var result in results)
        {
            var handler = DataContext.For<UIStudioVersionHandler>(result.Key);
            var version = await handler.Get();
            if (version != null)
            {
                versions.Add(version);
            }
        }

        return versions.OrderBy(v => v.DeleteAfter).ToList();
    }

    /// <summary>
    /// Compares two versions and generates a change summary.
    /// </summary>
    /// <param name="fromVersionNumber">Source version number</param>
    /// <param name="toVersionNumber">Target version number</param>
    /// <param name="resourceEntityId">Entity ID of the resource</param>
    /// <returns>Dictionary containing change information</returns>
    public async Task<Dictionary<string, object>?> CompareVersions(int fromVersionNumber, int toVersionNumber, Guid resourceEntityId)
    {
        var fromVersion = await GetVersion(resourceEntityId, fromVersionNumber);
        var toVersion = await GetVersion(resourceEntityId, toVersionNumber);

        if (fromVersion?.SnapshotData == null || toVersion?.SnapshotData == null)
        {
            return null;
        }

        // Basic comparison - can be enhanced with deep diff logic
        var changes = new Dictionary<string, object>
        {
            { "from_version", fromVersionNumber },
            { "to_version", toVersionNumber },
            { "from_checksum", fromVersion.SnapshotChecksum ?? "" },
            { "to_checksum", toVersion.SnapshotChecksum ?? "" },
            { "from_size", fromVersion.SnapshotSizeBytes },
            { "to_size", toVersion.SnapshotSizeBytes },
            { "has_changes", fromVersion.SnapshotChecksum != toVersion.SnapshotChecksum }
        };

        return changes;
    }

    /// <summary>
    /// Creates a manual version snapshot for a resource.
    /// </summary>
    /// <param name="resourceEntityId">Entity ID of the resource</param>
    /// <param name="resourceType">Type of the resource</param>
    /// <param name="snapshotData">Current state of the resource</param>
    /// <param name="createdByEntityId">Entity ID of the user creating the version</param>
    /// <param name="versionName">Name/label for this version</param>
    /// <param name="description">Description of this version</param>
    /// <returns>The created version component</returns>
    public async Task<UIStudioVersion> CreateManualVersion(
        Guid resourceEntityId, 
        string resourceType, 
        Dictionary<string, object> snapshotData,
        Guid createdByEntityId,
        string versionName,
        string? description = null)
    {
        var nextVersionNumber = await GetNextVersionNumber(resourceEntityId);
        
        var jsonData = JsonSerializer.Serialize(snapshotData);
        var version = new UIStudioVersion
        {
            ResourceEntityId = resourceEntityId,
            ResourceType = resourceType,
            VersionNumber = nextVersionNumber,
            SnapshotData = snapshotData,
            CreatedByEntityId = createdByEntityId,
            IsAutoGenerated = false,
            VersionLabel = versionName,
            ChangeSummary = description,
            SnapshotSizeBytes = Encoding.UTF8.GetByteCount(jsonData),
            SnapshotChecksum = CalculateChecksum(jsonData),
            RetentionPolicy = "manual" // Manual versions kept until explicitly deleted
        };

        return await CreateVersion(version);
    }

    /// <summary>
    /// Gets version history for a resource with pagination.
    /// </summary>
    /// <param name="resourceEntityId">Entity ID of the resource</param>
    /// <param name="limit">Maximum number of versions to return</param>
    /// <param name="offset">Number of versions to skip</param>
    /// <param name="includeAutoGenerated">Whether to include auto-generated versions</param>
    /// <returns>List of versions with pagination</returns>
    public async Task<List<UIStudioVersion>> GetVersionHistory(Guid resourceEntityId, int limit = 50, int offset = 0, bool includeAutoGenerated = true)
    {
        var query = DataContext.Query()
            .WithAll<UIStudioVersion>(v => v.ResourceEntityId == resourceEntityId);

        if (!includeAutoGenerated)
        {
            query = query.WithAll<UIStudioVersion>(v => !v.IsAutoGenerated);
        }

        var results = await query.ToEntityComponents();
        var versions = new List<UIStudioVersion>();

        foreach (var result in results)
        {
            var handler = DataContext.For<UIStudioVersionHandler>(result.Key);
            var version = await handler.Get();
            if (version != null)
            {
                versions.Add(version);
            }
        }

        return versions.OrderByDescending(v => v.VersionNumber)
                      .Skip(offset)
                      .Take(limit)
                      .ToList();
    }

    /// <summary>
    /// Gets the next version number for a resource.
    /// </summary>
    /// <param name="resourceEntityId">Entity ID of the resource</param>
    /// <returns>The next version number</returns>
    public async Task<int> GetNextVersionNumber(Guid resourceEntityId)
    {
        var latestVersion = await GetLatestVersion(resourceEntityId);
        return (latestVersion?.VersionNumber ?? 0) + 1;
    }

    /// <summary>
    /// Validates the version configuration.
    /// </summary>
    /// <param name="version">Version to validate</param>
    /// <exception cref="ArgumentException">Thrown when validation fails</exception>
    private static void ValidateVersionConfiguration(UIStudioVersion version)
    {
        if (version.ResourceEntityId == Guid.Empty)
        {
            throw new ArgumentException("Resource entity ID is required");
        }

        if (string.IsNullOrWhiteSpace(version.ResourceType))
        {
            throw new ArgumentException("Resource type is required");
        }

        if (version.VersionNumber <= 0)
        {
            throw new ArgumentException("Version number must be greater than 0");
        }

        if (version.CreatedByEntityId == Guid.Empty)
        {
            throw new ArgumentException("Created by entity ID is required");
        }
    }

    /// <summary>
    /// Calculates SHA256 checksum for the given data.
    /// </summary>
    /// <param name="data">Data to calculate checksum for</param>
    /// <returns>Hexadecimal checksum string</returns>
    private static string CalculateChecksum(string data)
    {
        using var sha256 = SHA256.Create();
        var hashBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(data));
        return Convert.ToHexString(hashBytes).ToLowerInvariant();
    }
}