using System.Security.Claims;
using core.jarvis.api.Services;

namespace core.jarvis.api.tests.Unit.Services;

/// <summary>
/// INTENT: Verify JWT token generation, validation, and refresh token operations
/// PURPOSE: Ensure secure token handling for authentication
/// BUSINESS CONTEXT: Tokens are the foundation of API security
/// WHY IMPORTANT: Token security prevents unauthorized access
/// ARCHITECTURAL SIGNIFICANCE: Enforces JWT standards and secure token practices
/// FUTURE RESILIENCE: Protects against token-based security vulnerabilities
/// </summary>
public class TokenServiceTests
{
    /// <summary>
    /// Test access token expiration time in minutes for test scenarios.
    /// Short duration appropriate for testing without impacting test execution time.
    /// </summary>
    private const int TestAccessTokenExpirationMinutes = 15;
    
    /// <summary>
    /// Expected size in bytes for refresh tokens generated by the service.
    /// Matches the implementation's 32-byte random token generation.
    /// </summary>
    private const int ExpectedRefreshTokenSizeBytes = 32;
    
    private readonly TokenService _tokenService;
    private readonly string _testSecretKey = "TEST_SECRET_KEY_WITH_AT_LEAST_256_BITS_FOR_SECURITY_TESTING_PURPOSES";

    public TokenServiceTests()
    {
        _tokenService = new TokenService("test-issuer", "test-audience", _testSecretKey, TestAccessTokenExpirationMinutes);
    }

    [Fact]
    public void AccessToken_Should_Create_Valid_JWT_Token()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var email = "test@example.com";

        // Act
        var token = _tokenService.AccessToken(userId, email);

        // Assert
        token.ShouldNotBeNullOrEmpty();
        token.Split('.').Length.ShouldBe(3); // JWT has 3 parts
    }

    [Fact]
    public void AccessToken_With_Additional_Claims_Should_Include_Claims()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var email = "test@example.com";
        var additionalClaims = new Dictionary<string, string>
        {
            { "role", "admin" },
            { "department", "IT" }
        };

        // Act
        var token = _tokenService.AccessToken(userId, email, additionalClaims);
        var principal = _tokenService.Validate(token);

        // Assert
        principal.ShouldNotBeNull();
        principal.FindFirst("role")?.Value.ShouldBe("admin");
        principal.FindFirst("department")?.Value.ShouldBe("IT");
    }

    [Fact]
    public void Validate_With_Valid_Token_Should_Return_Claims()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var email = "test@example.com";
        var token = _tokenService.AccessToken(userId, email);

        // Act
        var principal = _tokenService.Validate(token);

        // Assert
        principal.ShouldNotBeNull();
        principal.FindFirst(ClaimTypes.NameIdentifier)?.Value.ShouldBe(userId.ToString());
        principal.FindFirst(ClaimTypes.Email)?.Value.ShouldBe(email);
    }

    [Fact]
    public void Validate_With_Invalid_Token_Should_Return_Null()
    {
        // Arrange
        var invalidToken = "invalid.token.here";

        // Act
        var principal = _tokenService.Validate(invalidToken);

        // Assert
        principal.ShouldBeNull();
    }

    [Fact]
    public void RefreshToken_Should_Create_Unique_Tokens()
    {
        // Arrange & Act
        var token1 = _tokenService.RefreshToken();
        var token2 = _tokenService.RefreshToken();

        // Assert
        token1.ShouldNotBeNullOrEmpty();
        token2.ShouldNotBeNullOrEmpty();
        token1.ShouldNotBe(token2);
        Convert.FromBase64String(token1).Length.ShouldBe(ExpectedRefreshTokenSizeBytes);
    }

    [Fact]
    public void HashRefreshToken_Should_Create_Consistent_Hash()
    {
        // Arrange
        var refreshToken = _tokenService.RefreshToken();

        // Act
        var hash1 = _tokenService.HashRefreshToken(refreshToken);
        var hash2 = _tokenService.HashRefreshToken(refreshToken);

        // Assert
        hash1.ShouldNotBeNullOrEmpty();
        hash1.ShouldBe(hash2); // Same input produces same hash
    }

    [Fact]
    public void VerifyRefreshToken_With_Correct_Token_Should_Return_True()
    {
        // Arrange
        var refreshToken = _tokenService.RefreshToken();
        var hashedToken = _tokenService.HashRefreshToken(refreshToken);

        // Act
        var result = _tokenService.VerifyRefreshToken(refreshToken, hashedToken);

        // Assert
        result.ShouldBeTrue();
    }

    [Fact]
    public void VerifyRefreshToken_With_Incorrect_Token_Should_Return_False()
    {
        // Arrange
        var refreshToken1 = _tokenService.RefreshToken();
        var refreshToken2 = _tokenService.RefreshToken();
        var hashedToken = _tokenService.HashRefreshToken(refreshToken1);

        // Act
        var result = _tokenService.VerifyRefreshToken(refreshToken2, hashedToken);

        // Assert
        result.ShouldBeFalse();
    }

    [Fact]
    public void Validate_With_Wrong_Issuer_Should_Return_Null()
    {
        // Arrange
        var wrongIssuerService = new TokenService("wrong-issuer", "test-audience", _testSecretKey, TestAccessTokenExpirationMinutes);
        var userId = Guid.NewGuid();
        var email = "test@example.com";
        var token = wrongIssuerService.AccessToken(userId, email);

        // Act
        var principal = _tokenService.Validate(token);

        // Assert
        principal.ShouldBeNull();
    }

    [Fact]
    public void Validate_With_Wrong_Audience_Should_Return_Null()
    {
        // Arrange
        var wrongAudienceService = new TokenService("test-issuer", "wrong-audience", _testSecretKey, TestAccessTokenExpirationMinutes);
        var userId = Guid.NewGuid();
        var email = "test@example.com";
        var token = wrongAudienceService.AccessToken(userId, email);

        // Act
        var principal = _tokenService.Validate(token);

        // Assert
        principal.ShouldBeNull();
    }
}